name: UI CI/CD

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'ui/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./ui
    
    - name: Type check
      run: npx tsc --noEmit
      working-directory: ./ui
    
    - name: Run linting
      run: npm run lint
      working-directory: ./ui
      continue-on-error: true
    
    - name: Build
      run: npm run build
      working-directory: ./ui
